name: CI

on: [push]

jobs:
  build:

    runs-on: $
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and test container
      run: |
        chmod +x test.sh
        ./test.sh
